# .github/dependabot.yml

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location in the repository where dependabot should check for updates
    schedule:
      interval: "weekly" # Options: daily, weekly, monthly
    commit-message:
      prefix: "chore" # Customize commit message prefix (e.g., "chore", "build")
      prefix-development: "chore" # Optional, prefix for development dependencies
    reviewers:
      - "i-make-robots" # Optional, replace with GitHub usernames for PR review requests
    ignore:
      - dependency-name: "actions/checkout" # Optional, ignore updates for specific actions
