#!/bin/sh
# author: Peter Carlo Colapietro
# see: http://wynnnetherland.com/linked/2013012801/bootstrapping-consistency/
# see: https://github.com/bdemers/maven-wrapper
pushd script
source callmavenwrapper test
popd
